// This file contains the tables generated by various functions of the program along with a breakdown of what each aspect means.

//User Table - Exactly what you'd think. This table is what would be generated when a new user is created by the program. the ft_name string stands for first name, andthe lt_name stands for last name.

create table User (
	idnum int unsigned auto_increment not null,
	username varchar(32) not null,
	fr_name varchar(32) not null.
	lt_name varchar(32) not null,
	email varchar(32) not null,
	dt_joined timestamp default now(),
	           )

//Event Table - The most important table. This contains the actual data about volunteering events. Org stands for orgaanization, and it's to group volunteer hours withorganizations together, and volunteer hours that a user performed independently. Location is also to group repeated volunteer hours in the same place.

create table Event (
	eventid int unsigned auto_increment not null,
	hrs_worked int unsigned not null,
	org boolean not null,
	location varchar (32) not null,	    
		    )

